Serilog: # Logging configuration: https://github.com/serilog/serilog-settings-configuration
  Using:
    - Serilog.Sinks.Console
  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <{SourceContext}>{NewLine}{Exception}"
  MinimumLevel: Debug # Information, Warning, Error, Fatal
  Enrich:
    - FromLogContext

App:
  Locale:
    Placeholder: Probing...
    Measurements: 
      # You can omit configuration for a specific measurement to use default labels
      # Available measurements: CO2, Temp, Humidity, PM25, PM10, TVOC, ETVOC, Battery, Noise
      Temp:
        Name: Temperature
        Measurement: C

Telegram:
  Token: "YOUR_TELEGRAM_BOT_TOKEN"
  AntispamDuration: 10  # Time in seconds between command calls in the same chat
  AllowedChats:  # List of chat IDs where the bot can be used
    - 0 # Allow to be used in any chat
    - 123456
    - -123456
  Command:
    Name: temp  # custom command name, temp by default (so /temp@yourbotname)
    Description: Get thermostat data

Cleargrass:
  Cpps:
    defman:  # Unique identifier
      Key: SOME-KEY
      Secret: someverysecretvalue
    notdefman:
      Key: SOME-OTHER-KEY
      Secret: somesupersecretvalue
  Devices:
    ABCDEF1234:
      RoomName: Bedroom
      OwnerUsername: defman
